### ISSUE TITLE
sysdeps for ppc platforms

### ISSUE THREAD

**Issue by q66** [CMB/skaware-void-sysdeps#10]
Would it be possible to also generate them for the ppc64/ppc platforms?

Particularly these triples:

```
powerpc64le-linux-gnu
powepc64le-linux-musl
powerpc64-linux-gnu
powerpc64-linux-musl
powerpc-linux-gnu
powerpc-linux-musl
```

Alternatively I can generate them myself, I have all the 64-bit ppc stuff available natively, if you ping me when planning to generate a new archive.

**Comment by CMB** [comment]
Daniel Kolesa (notifications@github.com) writes:

> Would it be possible to also generate them for the ppc64/ppc platforms?

Sure.  Right now I mostly use chroots to generate them.  The hardware I
have access to is armv7, aarch64, and x86_64.  In the past, before I had
native aarch64, I used a chroot with qemu-user-static to generate
sysdeps for that arch.  So technically a native environment isn't
needed.  In this case, it is helpful, because I don't find any prebuilt
Void rootfs tarballs for PPC.
To be honest, I'm not really sure what the state of Void on PPC is right
now.

I'd be glad to take your sysdeps and include them in the bundle I build
for Void.

-- Chris

**Comment by q66** [comment]
void-ppc64 is a new port maintained by me, currently a fork, but I'm merging upstream continuously (almost all changes are upstream) and i provide a separate binary repo, which has most packages available in void-packages built. I haven't built any rootfs tarballs yet, but I will soon. See https://void-ppc64.octaforge.org ... There is a separate 32-bit porting effort which is also largely merged but I'm not in charge of it. I provide skalibs because I have a powerful native builder, so no cross needed, but it'd still be useful to have cross compiling support for it

**Comment by CMB** [comment]
skalibs 2.8.1.0 is out.  If you want to send along PPC sysdeps, I'll
publish them.

**Comment by q66** [comment]
Sure. I have the 64-bit ones generated already, just trying to see if I can also get a 32-bit environment set up, so that I can send them all at once. I might send them all tonight

**Comment by q66** [comment]
Here https://github.com/CMB/skaware-void-sysdeps/pull/11

**Comment by CMB** [comment]
Thank you!
That is merged.  I'll close this ticket.
